const loginCard=document.querySelector('#login-card'),editor=document.querySelector('#editor');let client,currentContent={},user;
const msg=(id,text,kind='')=>{const el=document.querySelector(id);el.textContent=text;el.className=`message ${kind}`};
const configured=()=>window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_URL.includes('YOUR_');
async function admin(){const {data}=await client.from('profiles').select('role').eq('id',user.id).single();return data?.role==='admin'}
async function load(){const {data}=await client.from('site_content').select('*').eq('id','home').single();currentContent=data||{};['title','description','button_text','button_url','body'].forEach(k=>document.querySelector(`#${k}`).value=currentContent[k]||'');if(currentContent.image_url){preview.src=currentContent.image_url;document.querySelector('#preview-wrap').hidden=false}}
async function session(){const {data:{session}}=await client.auth.getSession();if(!session)return;user=session.user;if(!await admin()){await client.auth.signOut();return msg('#login-message','이 계정에는 관리자 권한이 없습니다.','error')}loginCard.hidden=true;editor.hidden=false;load()}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();if(!configured())return msg('#login-message','먼저 supabase-config.js를 설정하세요.','error');const {data,error}=await client.auth.signInWithPassword({email:email.value,password:password.value});if(error)return msg('#login-message',error.message,'error');user=data.user;if(!await admin()){await client.auth.signOut();return msg('#login-message','이 계정에는 관리자 권한이 없습니다.','error')}loginCard.hidden=true;editor.hidden=false;load()});
document.querySelector('#logout').addEventListener('click',async()=>{await client.auth.signOut();editor.hidden=true;loginCard.hidden=false});
document.querySelector('#content-form').addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;msg('#save-message','저장 중…');let image_url=currentContent.image_url||'';const file=image.files[0];if(file){const ext=file.name.split('.').pop(),path=`home/${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('images').upload(path,file);if(error){save.disabled=false;return msg('#save-message',error.message,'error')}image_url=client.storage.from('images').getPublicUrl(path).data.publicUrl}const record={id:'home',title:title.value.trim(),description:description.value.trim(),button_text:button_text.value.trim(),button_url:button_url.value.trim(),body:body.value.trim(),image_url,updated_at:new Date().toISOString()};const {error}=await client.from('site_content').upsert(record);save.disabled=false;if(error)return msg('#save-message',error.message,'error');currentContent=record;if(image_url){preview.src=image_url;document.querySelector('#preview-wrap').hidden=false}msg('#save-message','저장했습니다. 공개 페이지에 바로 반영됩니다.','success')});
if(configured()){client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);session()}else msg('#login-message','Supabase 연결 설정이 필요합니다.','error');
